name: clean_architecture_template
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  # presentation only deps
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7


dev_dependencies:
  bloc_test: ^9.1.5
  build_runner:
  freezed: ^2.4.6
  lint: ^2.3.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
